### ISSUE TITLE
ProPeek CallingModules and CalledModules double click input search displayed incorrectly

### ISSUE THREAD

**Issue by abelzis** [BalticAmadeus/ProPeek#150]
Steps to reproduce:

1. Open a profiler file.
2. Double click on any of the Calling Modules or Called Modules lines.
3. Notice the input of the module name in Module Details.

![Image](https://github.com/BalticAmadeus/ProPeek/assets/44312404/cea05c03-817e-4da5-b7c6-0fc931705c29)

Sometimes the value is not displayed, or is displayed only when clicked on the input box. Also, removing the value, the screen is not updated.

**Comment by hjuknonis** [comment]
Also noticed that when module details is filtered after double click, it always displays the data of the first module in the list while sometimes the actual module is not the first (as in screenshot below, it would display the pauseFunc internal function instead of test1 procedure file). Also keep in mind that there could be overloaded methods with exactly the same name and the wrong one could be displayed even if the filtered line name identically matches the input.

![image](https://github.com/BalticAmadeus/ProPeek/assets/43231236/1f153929-ff87-4984-9044-f2edcfb79392)

Maybe it would be possible to extract ModuleID from the line which was double clicked on Calling/Called Modules and filter module details based on that? Although that might be more challenging to do when double clicking on Flame graph nodes which also filters Module details tab.
